version: '3'

services:
  emqx1:
    image: emqx/emqx-ee:4.3.5
    environment:
      - "EMQX_NAME=emqx"
      - "EMQX_HOST=node1.emqx.io"
      - "EMQX_CLUSTER__DISCOVERY=static"
      - "EMQX_CLUSTER__STATIC__SEEDS=emqx@node1.emqx.io, emqx@node2.emqx.io"
      - "EMQX_ZONE__EXTERNAL__RETRY_INTERVAL=2s"
      - "EMQX_MQTT__MAX_TOPIC_ALIAS=10"
    volumes:
      - ./dev_run/emqx/emqx.lic:/opt/emqx/etc/emqx.lic
      - ./dev_run/emqx/emqx.key:/opt/emqx/etc/emqx.key
    ports:
      - 1883:1883
      - 8083:8083
      - 4369:4369
      - 18083:18083
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    networks:
      emqx-bridge:
        aliases:
          - node1.emqx.io

#  emqx2:
#    image: emqx/emqx:v4.0.0
#    environment:
#      - "EMQX_NAME=emqx"
#      - "EMQX_HOST=node2.emqx.io"
#      - "EMQX_CLUSTER__DISCOVERY=static"
#      - "EMQX_CLUSTER__STATIC__SEEDS=emqx@node1.emqx.io, emqx@node2.emqx.io"
#      - "EMQX_ZONE__EXTERNAL__RETRY_INTERVAL=2s"
#      - "EMQX_MQTT__MAX_TOPIC_ALIAS=10"
#    volumes:
#      - ./dev_run/emqx/emqx.lic:/opt/emqx/etc/emqx.lic
#    healthcheck:
#      test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
#      interval: 5s
#      timeout: 25s
#      retries: 5
#    networks:
#      emqx-bridge:
#        aliases:
#          - node2.emqx.io

  client:
    image: python:3.7.2-alpine3.9
    depends_on:
      - emqx1
#      - emqx2
    tty: true
    networks:
      emqx-bridge:

networks:
  emqx-bridge:
    driver: bridge