definitions:
  account.User:
    properties:
      email:
        description: 邮箱
        example: 123@ee.com
        type: string
      password:
        description: 密码
        example: 123@password
        type: string
      username:
        description: 用户名
        example: mick
        type: string
    type: object
  coach.AthleteTraining:
    properties:
      acceleration:
        description: 功率（加速度）
        type: number
      athlete_id:
        description: 运动员ID
        type: integer
      athlete_name:
        description: 运动员姓名
        type: string
      athlete_training_status:
        type: boolean
      average_speed:
        description: 平均时速
        type: number
      distance:
        description: 距离（路程）
        type: number
      instantaneous_propeller_speed:
        description: 瞬时桨速
        type: number
      instantaneous_speed:
        description: 瞬时时速
        type: number
      sport_img:
        description: 运动员头像
        type: string
      status:
        description: 当前状态
        type: string
      stroke:
        description: 划行距离
        type: number
      total_oars:
        description: 总桨数
        type: integer
    type: object
  errs.BasicError:
    properties:
      code:
        type: string
      msg:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/mc/v1/account/:username:
    get:
      description: 传入 username，根据用户名查询用户
      parameters:
      - description: nick
        in: path
        name: username
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/account.User'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errs.BasicError'
      summary: 获取用户信息
  /api/v1/coach/training:
    get:
      description: 实时训练数据
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/coach.AthleteTraining'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errs.BasicError'
      summary: 获取实时训练数据
swagger: "2.0"
